
results_path: workflow/output

ImageRetrieval:
  api_key: ''
  service: bing
  zoom: 19
  output_folder: satellite
  bbox:
    min_lat: 50.76900107193788
    min_lon: 6.097842567710818
    max_lat: 50.76379834423302
    max_lon: 6.111769276140406
  
  #shapefile: 'workflow/input/aachen/aachen.shp'

ImageSegmentation:
  output_folder: 'segmentation'
  model_rel_path: 'model/rooftop_segmentation.h5'
  osm: True
  tile_size: 512
  stride: 256
  save_masks: True
  save_filtered: True
  # Does not apply to osm:
  polygon_simplification_distance: 15
  kernel_size: 18 # For morphological opening and closing
  # Does not apply to model:
  osm_request_interval: 30

RooftopAnalysis:
  output_folder: 'rooftops'
  file_name: 'rooftops'
  minimum_area: 100

SectionAnalysis:
  output_folder: 'sections'
  file_name: 'sections'
  tilt_rel_path: 'tilt_distribution.pkl'
  
TechnicalAnalysis:
  output_folder: 'technical'
  file_name: 'technical'
  era5_path: '/storage/internal/data/gears/weather/ERA5/processed/4/8/5/2016'
  sarah_path: '/storage/internal/data/gears/weather/SARAH/processed/4/8/5/2016'
  
EconomicAnalysis:
  output_folder: 'economic'
  file_name: 'lcoe'

SegmentationTraining:
  dataset_folder: '/storage/internal/data/r-pueblas/aachen_model/'
  output_folder: 'model'
  file_name: 'rooftop-segmentation'
  batch_size: 2
  n_epochs: 30
  steps_per_epoch: 5000
  val_steps: 200