
results_path: workflow/output
project_name: skopje

ImageRetrieval:
  api_key: ''
  service: bing
  zoom: 19
  output_folder: satellite
  bbox:
    min_lat: 42.00250900219151
    min_lon: 21.37517907059881
    max_lat: 42.006949557339766
    max_lon: 21.383691965463324
  #shapefile: 'workflow/input/kreuzberg/297622950.shp'

RooftopSegmentation:
  output_folder: 'segmentation/rooftops'
  model_rel_path: 'model/rooftop-segmentation/inria-aug-10e.pth'
  osm: False
  tile_size: 512
  stride: 512
  # Does not apply to osm:
  background_class: 0
  polygon_simplification_distance: 6
  kernel_size: 7 # For morphological opening and closing
  # Does not apply to model:
  osm_request_interval: 30
  osm_output_folder: 'segmentation/osm'

SectionSegmentation:
  output_folder: 'segmentation/sections'
  model_rel_path: 'model/section-segmentation/sections-mix-aug.pth'
  tile_size: 512
  stride: 512
  background_class: 17
  polygon_simplification_distance: 6
  kernel_size: 7 # For morphological opening and closing
  
SuperstructureSegmentation:
  output_folder: 'segmentation/superstructures'
  model_rel_path: 'model/pv-segmentation/rid-mix_best.pth'
  tile_size: 512
  stride: 512
  background_class: 8
  polygon_simplification_distance: 6
  kernel_size: 7 # For morphological opening and closing

RooftopAnalysis:
  output_folder: 'rooftops'
  file_name: 'rooftops'
  superstructures_file_name: 'superstructures'
  minimum_area: 20
  tilt_rel_path: 'tilt_distribution.pkl'

TechnicalAnalysis:
  output_folder: 'technical'
  file_name: 'technical'
  era5_path: '/storage/internal/data/gears/weather/ERA5/processed/4/8/5/2017'
  #era5_path: '/storage/internal/home/r-pueblas/projects/other/RESKit/reskit/_test/data/era5-like'
  sarah_path: '/storage/internal/data/gears/weather/SARAH/processed/4/8/5/2017'
  #sarah_path: '/storage/internal/home/r-pueblas/projects/other/RESKit/reskit/_test/data/sarah-like'
  pv_model_id: 'LG Electronics LG370Q1C-A5' # RESKit identifier
  pv_model_name: 'LG370Q1C-A5'
  pv_model_capacity: 370 # kW
  pv_model_width: 1.7 # meters
  pv_model_height: 1.016 # meters
  pv_model_price: 350 # euros
  pv_spacing_factor: 1.2
  pv_border_spacing: 1.5 # meters
  pv_n_offset: 7
  
EconomicAnalysis:
  output_folder: 'economic'
  file_name: 'lcoe'

SectionSegmentationTraining:
  train_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/RID/output/masks_segments_reviewed_aug/train'
  val_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/RID/output/masks_segments_reviewed/val'
  output_folder: 'model'
  folder_name: 'section-segmentation'
  model_name: 'sections-mix-aug.pth'
  num_classes: 18
  batch_size: 8
  learning_rate: 0.00001
  n_epochs: 10

RooftopSegmentationTraining:
  train_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/INRIA/output/train_aug'
  val_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/INRIA/output/val_aug'
  output_folder: 'model'
  folder_name: 'rooftop-segmentation'
  model_name: 'inria-aug-10e.pth'
  num_classes: 2
  batch_size: 8
  learning_rate: 0.00001
  n_epochs: 10

SuperstructureSegmentationTraining:
  train_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/RID/output/masks_superstructures_reviewed_aug/train'
  val_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/RID/output/masks_superstructures_reviewed/val'
  output_folder: 'model'
  folder_name: 'pv-segmentation'
  model_name: 'rid-mix_best.pth'
  num_classes: 9
  batch_size: 8
  learning_rate: 0.00001
  n_epochs: 10