
results_path: workflow/output
project_name: dresde-test-model-prioritize

ImageRetrieval:
  api_key: ''
  service: bing
  zoom: 19
  output_folder: satellite
  bbox:
    min_lat: 50.780540206411494
    min_lon: 6.075009080646369
    max_lat: 50.769610743766044
    max_lon: 6.094732826367578

  #shapefile: 'workflow/input/apeldoorn/308148215.shp'

RooftopSegmentation:
  output_folder: 'segmentation/rooftops'
  model_rel_path: 'model/rooftop-segmentation/rooftops.pth'
  osm: False
  tile_size: 512
  stride: 512
  # Does not apply to osm:
  background_class: 0
  opening_closing_kernel: 7 # For morphological opening and closing
  erosion_kernel: 15 # For erosion
  # Does not apply to model:
  osm_request_interval: 5
  num_retries: 5
  osm_output_folder: 'segmentation/rooftops'

SectionSegmentation:
  output_folder: 'segmentation/sections'
  model_rel_path: 'model/section-segmentation/sections.pth'
  tile_size: 512
  stride: 512
  background_class: 17
  opening_closing_kernel: 7 # For morphological opening and closing
  erosion_kernel: 1 # For erosion
  
SuperstructureSegmentation:
  output_folder: 'segmentation/superstructures'
  model_rel_path: 'model/superst-segmentation/superstructures.pth'
  tile_size: 512
  stride: 512
  background_class: 8
  opening_closing_kernel: 7 # For morphological opening and closing
  erosion_kernel: 1 # For erosion

RooftopAnalysis:
  output_folder: 'rooftops'
  file_name: 'rooftops'
  superstructures_file_name: 'superstructures'
  tilt_rel_path: 'tilt_distribution.pkl'
  simplification_distance: 0.2
  merge_style: prioritize-rooftops # [intersection, prioritize-rooftops, union]

TechnicalAnalysis:
  output_folder: 'technical'
  file_name: 'technical'
  #merra_path: '/storage/internal/home/r-pueblas/projects/other/RESKit/reskit/_test/data/merra-like'
  merra_path: '/storage/internal/data/tsa/data/weather/merra2/europe/2016/'
  #solar_atlas_path: '/storage/internal/home/r-pueblas/projects/other/RESKit/reskit/_test/data/gsa-ghi-like.tif'
  solar_atlas_path: '/storage/internal/data/tsa/data/geography/world_bank_group/global_solar_atlas/World_GHI_GISdata_LTAy_DailySum_GlobalSolarAtlas_GEOTIFF/GHI.tif'
  minimum_section_area: 20
  pv_model_id: 'LG Electronics LG370Q1C-A5' # RESKit identifier
  pv_model_name: 'LG370Q1C-A5'
  pv_model_capacity: 370 # kW
  pv_model_width: 1.7 # meters
  pv_model_height: 1.016 # meters
  pv_model_price: 350 # euros
  pv_spacing_factor: 1.3
  pv_border_spacing: 1.5 # meters
  pv_n_offset: 7
  
EconomicAnalysis:
  output_folder: 'economic'
  file_name: 'lcoe'
  panel_lifespan: 25
  inverter_lifespan: 13
  inverter_price_rate: 0.2
  other_costs: 200
  discount_rate: 0.08
  yearly_degradation: 0.005

SectionSegmentationTraining:
  train_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/RID/output/masks_segments_reviewed/train'
  val_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/RID/output/masks_segments_reviewed/val'
  output_folder: 'model'
  folder_name: 'section-segmentation'
  model_name: 'sections.pth'
  num_classes: 18
  batch_size: 8
  learning_rate: 0.00001
  n_epochs: 20

RooftopSegmentationTraining:
  train_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/INRIA/output/train'
  val_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/INRIA/output/val'
  output_folder: 'model'
  folder_name: 'rooftop-segmentation'
  model_name: 'rooftops.pth'
  num_classes: 2
  batch_size: 8
  learning_rate: 0.00001
  n_epochs: 12

SuperstructureSegmentationTraining:
  train_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/RID/output/masks_superstructures_reviewed/train'
  val_folder: '/storage/internal/home/r-pueblas/projects/rooftop-segmentation-datasets/data/RID/output/masks_superstructures_reviewed/val'
  output_folder: 'model'
  folder_name: 'superst-segmentation'
  model_name: 'superstructures.pth'
  num_classes: 9
  batch_size: 8
  learning_rate: 0.00001
  n_epochs: 20