
results_path: workflow/output

ImageRetrieval:
  api_key: ''
  service: bing
  zoom: 19
  output_folder: satellite
  bbox:
    min_lat: 50.77850739604879
    min_lon: 6.0768084397936395
    max_lat: 50.77214558009357
    max_lon: 6.091035433169415
  
  #shapefile: 'workflow/input/aachen/aachen.shp'

ImageSegmentation:
  output_folder: 'segmentation'
  model_rel_path: 'model/rooftop_segmentation.h5'

RooftopAnalysis:
  output_folder: 'rooftops'
  file_name: 'rooftops'
  minimum_area: 25

SectionAnalysis:
  output_folder: 'sections'
  file_name: 'sections'
  tilt_rel_path: 'tilt_distribution.pkl'
  
TechnicalAnalysis:
  output_folder: 'technical'
  file_name: 'technical'
  era5_path: '/storage/internal/data/gears/weather/ERA5/processed/4/8/5/2016'
  sarah_path: '/storage/internal/data/gears/weather/SARAH/processed/4/8/5/2016'
  
EconomicAnalysis:
  output_folder: 'economic'
  file_name: 'lcoe'