name: passion-gui
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - gdal=3.2.1
  - notebook=6.4.0
  - pip=22.0.4
  - pip:
    - opencv-python-headless==4.6.0.66
    - descartes==1.1.0
    - efficientnet==1.0.0
    - gast==0.4.0
    - https://github.com/FZJ-IEK3-VSA/geokit/archive/v1.3.0.zip
    - image-classifiers==1.0.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - mahotas==1.4.11
    - markdown==3.3.4
    - matplotlib==3.4.2
    - netcdf4==1.5.7
    - networkx==2.6.2
    - numpy==1.20.0
    - pandas==1.3.1
    - pillow==8.3.1
    - pvlib==0.8.1
    - py==1.10.0
    - pyshp==2.1.3
    - pytest==6.2.4
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - git+https://github.com/FZJ-IEK3-VSA/reskit.git#egg=reskit
    - rsa==4.7.2
    - scikit-image==0.18.2
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - segmentation-models==1.0.1
    - shapely==1.7.1
    - six==1.15.0
    - smopy==0.0.7
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - termcolor==1.1.0
    - tqdm==4.61.2
    - urllib3==1.26.6
    - wrapt==1.12.1
    - xarray==0.19.0
    - snakemake
    - flask==2.1.2
    - folium==0.12.1.post1
    - geopandas==0.11.1
    - .