import pathlib
import numpy as np
import tqdm
import shapely.geometry

import passion.util

def generate_osm(input_path: pathlib.Path,
                    output_path: pathlib.Path,
                    save_masks: bool = True,
                    save_filtered: bool = True,
                    osm_request_interval: float = 5
):
  '''Segments a full dataset generated by generate_dataset(),
  saving the open OSM footprints as segmented masks
  in the specified folder.

  Input images must have the naming format specified by gis.get_filename().

  Segmented images are saved with the same name as the original
  images appending '_MASK' in the end.

  ---
  
  input_path      -- Path, folder in which image_retrieval dataset was generated.
  output_path     -- Path, folder in which masks and filtered images will be stored.
  save_masks      -- bool, if specified the masks will be stored.
  save_filtered   -- bool, if specified the filtered images will be stored.
  '''
  output_path.mkdir(parents=True, exist_ok=True)

  paths = list(input_path.glob('*.png'))
  pbar = tqdm.tqdm(paths)
  for img_path in pbar:
    image = passion.util.io.load_image(img_path)

    latlon, zoom = passion.util.gis.extract_filename(img_path.stem)

    seg_image = segment_img(image, latlon, zoom, osm_request_interval)

    seg_image = postprocess_output(seg_image)

    if save_masks: passion.util.io.save_image(seg_image, output_path, img_path.stem + '_MASK' + '.png')

    if save_filtered:
      filtered_image = passion.util.shapes.filter_image(image, seg_image)
      passion.util.io.save_image(filtered_image, output_path, img_path.stem + '_FILTERED' + '.png')
  return

def segment_img(image: np.ndarray, latlon: tuple, zoom: int, osm_request_interval: float = 5):
  ''''Segments a single image in numpy format with
  the open OSM footprints. 
  
  Returns a binary numpy image.'''

  if type(image) != np.ndarray:
    print('Image type: {0} not a np.array'.format(type(image)))
    return None
  if len(image.shape) != 3 or image.shape[-1] != 3:
    print('Image shape: {0} not in format MxNx3'.format(image.shape))
    return None

  bbox = passion.util.gis.get_image_bbox(latlon, zoom, image.shape)

  img_buildings = passion.util.osm.get_footprints_latlon(bbox, osm_request_interval)

  img_buildings_xy_abs = [ [ (passion.util.gis.latlon_toXY(coord[0], coord[1], zoom)) for coord in building ] for building in img_buildings ]

  offset_x, offset_y = passion.util.gis.get_image_offset(bbox, zoom)

  img_buildings_xy = [ [ (coord[0]-offset_x, coord[1]-offset_y) for coord in building] for building in img_buildings_xy_abs]

  img_buildings_polygons = [ shapely.geometry.Polygon(building) for building in img_buildings_xy]

  seg_image = passion.util.shapes.outlines_to_image(img_buildings_xy, image.shape[:2])

  return seg_image

def postprocess_output(image: np.ndarray):
  '''Transformations that are made to the output of the retrieved OSM footprints.
  
  No transformations are made by default, this method has to be overwritten.

  Returns a numpy image.
  '''
  return image